spring:
  data:
    mongodb:
      username: shopping
      password: shopping
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: OrderConfirmation:com.shop.notification.kafka.order.OrderConfirmation,PaymentConfirmation:com.shop.notification.kafka.payment.PaymentConfirmation
  mail:
    host: localhost
    port: 1025
    username: shopping
    password: shopping
    properties:
      mail:
        smtp:
          trust: '*'
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

server:
  port: 8040